### ISSUE TITLE
Propose aeternity key formats

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-wallet#67]

**Comment by gspasov** [comment]
Firstly for generating the master key and chain code using this function 
```:crypto.hmac(:sha512, "Bitcoin seed", seed)```
we can just change the key value and do it like the following
```:crypto.hmac(:sha512, "Aeternity seed", seed)```

This ensures that the derived key is going to be different from the bitcoin one.

For the extended keys I propose to keep the derivation method and only change the version bytes. So where the bitcoin keys start with xprv and xpub for the mainnet and tprv and tpub for the testnet, to be changed with aepv and aeub for mainnet and tepv and teub for testnet. 
The version bytes will go like this:
```aepv = <<158, 133, 10, 201>> = 0x9E850AC9```
```aeub = <<158, 134, 183, 142>> = 0x9E86B78E```

```tepv = <<243, 79, 46, 50>> = 0xF34F2E32```
```teub = <<243, 80, 218, 248>> = 0xF350DAF8```

For the Address the Bitcoin version has a prefix of 1, for Aeternity we can do the prefix with "A". So we'll be using the following network version values:
```Mainnet: <<24>> = 0x18 Starting index A```
```Testnet: <<"B">> = 0x42 Starting index T```

**Comment by thepiwo** [comment]
Will using longer prefixes break the key generation?

**Comment by gspasov** [comment]
## Prefixes
I'm not quite sure about that, I must test it. The way I created the prefixes is the way other altcoins do it. So for example for DogeCoin the prefixes are dgpv and dgub on the mainnet and so forth. Maybe it's not the most thoughtful way of doing it, but I'm not sure if we would prefer or (if even makes sense) to create another derivation method for the master (private) key or the extended keys.

## Address
Maybe we can do something different for the Address, because I've read that there could be some improvements done there, over the Bitcoin way. 

One criticism is that bitcoin addresses should be deprecated in favor of a more user-friendly mechanism for payments, and that this will just encourage continued use of a poorly designed mechanism.

Another criticism is that bitcoin addresses are inherently insecure because there is no identity information tied to them; if you only have a bitcoin address, how can you be certain that you're paying who or what you think you're paying?

Furthermore, truncating SHA256 is not an optimal checksum; there are much better error-detecting algorithms. If we are introducing a new form of Bitcoin address, then perhaps a better algorithm should be used.

_Taken from the BIP-13, for further read go to_ [BIP-13](https://github.com/bitcoin/bips/blob/master/bip-0013.mediawiki#rationale)

**Comment by thepiwo** [comment]
What would your proposal for improved addresses be?

The identity problem will be solved by aeternity using a naming system where readable and memorable names can be attached to accounts.

**Comment by thepiwo** [comment]
Can you commit code where the changes are integrated? It would be great if the test-cases use bitcoin prefixes and wif, to match the specification. And you can use the aeternity proposal optionally.

**Comment by gspasov** [comment]
Well, I haven given it much though about how the addresses could be improved. I just stumbled upon this information when I was researching for a way to distinguish ourselves from the other addresses. Now when I thing about it more, why would one want to be identified by his address, this is against the point of cryptocurrencies. Wasn't the point everything to be anonymous?

As far as the aeternity proposal goes. What do you mean by account? Are this names going to be attached to a wallet account or a public key?

Yes, I can integrate the aeternity prefixes. But that way I cannot make the test work with Bitcoin keys, unless I make some change in the code so that you can choose between Bitcoin and Aeternity prefixes. And I haven't integrated WIF formatting.

**Comment by gspasov** [comment]
Yes, I can do it. It won't be much work the way I've made the code.

Okay, so the names would have some relation to the key? If I write a key it would give me the name it is attached to (if it has one)?

**Comment by thepiwo** [comment]
Yes!

**Comment by thepiwo** [comment]
@gspasov have you checked if there are collisions with other cryptocurrencies using the same key formats?

**Comment by gspasov** [comment]
@thepiwo no, not really. Should I go through the internet and check (even though I'm not really sure how I'll go about it)?

**Comment by thepiwo** [comment]
there should be some list of already used key formats/prefixes

**Comment by thepiwo** [comment]
did you check for conflicts?

**Comment by gspasov** [comment]
@thepiwo 
I haven't found conflicts for the prefixes for now. But I cannot be completely sure. There are so many different tokens and the isn't a list specifying the prefixes they use. But if we do find, I'll change the prefixes.

**Comment by clarkmoody** [comment]
SatoshiLabs has recently added [SLIP-32](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) to act as a registry for HD seed version bytes, including the various address derivation schemes surrounding SegWit. Pull Requests are welcome for new coin entries!

**Comment by thepiwo** [comment]
@clarkmoody thank you, thats great!
